name: Deploy Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy para produção
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Simular deploy
        run: echo "Deploying to $PROD_DOMAIN"
        env:
          PROD_DOMAIN: ${{ vars.PROD_DOMAIN }}